phases:
  pre_build:
    commands:
      -mvn clean install
      -echo Logging in to Amazon ECR...
      -aws --version
      -$ (aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      -REPOSITORY_URI=REGISTRY_URI
      -COMMIT HASH=
      -IMAGE_TAG=$(echo $CODEBUILD_BUILD_id | awk -F":" '{print $2}')
  build:
   commands:
     -echo Build started on `date`
     -echo Building the Docker image...
     -docker build -t $REPOSITORY_URI:LATEST .
     -docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
     -echo Build started on `date`
     -echo Building the Docker image...
     -docker push $REPOSITORY_URI:LATEST .
     -docker push $REPOSITORY_URI:$IMAGE_TAG
     -echo Writing image definition file...
     printf '[{"name":"order-service","imageUri":"&s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinition.json
     -cat imagedefinition.json
artifacts:
  files:
    -imagedefinition.json
    -target/order-service.jar
